Repository Dragos-Florin-Pojoga/ChessFlow, pull requests merged in 2025-05, with the labels that each got.

#49 First GM version
  .idea/.gitignore
  .idea/vcs.xml
  GM/.gitignore
  GM/.idea/.gitignore
  GM/.idea/HelloRust2.iml
  GM/.idea/modules.xml
  GM/.idea/vcs.xml
  GM/Cargo.lock
  GM/Cargo.toml
  GM/src/main.rs
Labels: GM

#51 Engine
  engine/.cargo/config.toml
  engine/.gitignore
  engine/Cargo.toml
  engine/Makefile
  engine/public/engine.js
  engine/public/worker.js
  engine/rust-toolchain
  engine/src/chess_lib.rs
  engine/src/chess_lib/bitboard.rs
  engine/src/chess_lib/board.rs
  engine/src/chess_lib/evaluate.rs
  engine/src/chess_lib/moves.rs
  engine/src/chess_lib/search.rs
  engine/src/chess_lib/simple_pst.rs
  engine/src/chess_lib/terminal_states.rs
  engine/src/chess_lib/uci_executor.rs
  engine/src/chess_lib/uci_parser.rs
  engine/src/native_main.rs
  engine/src/wasm_main.rs
  engine/test_web_server.py
  engine/tests/automated_response_tests.html
  engine/tests/interactive_parse_test.html
  engine/tests/multithreading_test.html
  engine/tests/testpage.html
Labels: Engine

#52 Docs
  README.md
  docs/Patterns.md
  docs/Proompting.md
  docs/README.md
  docs/Standards.md
  docs/prezentare_checkpoint2/cod_LateX.tex
  docs/prezentare_checkpoint2/prezentare-checkpoint-2.pdf
Labels: documentation
